-- Clinician review queue (Phase 7).
--
-- When a request needs a human (a red-flag referral, an escalation, a second look at
-- a capture), it is placed on a queue that a licensed clinician works. This table is
-- the durable queue: it holds the request, its priority, the SLA deadline, who is
-- assigned, the reviewer's sign-off, and an escalation trail. It holds NO clinical
-- content of its own — any wording comes from a reviewed pack.
--
-- Idempotent: `CREATE TABLE IF NOT EXISTS` and `CREATE INDEX IF NOT EXISTS`.

CREATE TABLE IF NOT EXISTS review_queue (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id        TEXT NOT NULL DEFAULT 'default',
  -- The user whose request this is (FK to users, delete cascade).
  subject_user_id  UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- Optional dependant the request is about.
  dependent_id     UUID REFERENCES dependents(id) ON DELETE CASCADE,
  -- What kind of review this is, e.g. red_flag_referral / capture_review.
  kind             TEXT NOT NULL,
  -- A pack id + version pin so the reviewer sees exactly what the user saw.
  pack_id          TEXT,
  pack_version     TEXT,
  priority         INTEGER NOT NULL DEFAULT 0,
  status           TEXT NOT NULL DEFAULT 'queued'
                     CHECK (status IN ('queued', 'in_review', 'resolved', 'escalated', 'cancelled')),
  -- The clinician assigned (FK to users, no cascade so the trail survives).
  assigned_user_id UUID REFERENCES users(id),
  -- SLA deadline the queue is measured against.
  sla_due_at       TIMESTAMPTZ,
  -- Reviewer sign-off: who and when. Null until a human resolves it.
  reviewed_by      UUID REFERENCES users(id),
  reviewed_at      TIMESTAMPTZ,
  -- Free-text reviewer note (no clinical content is generated by the app).
  review_note      TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS review_queue_status_idx
  ON review_queue (tenant_id, status, priority DESC, created_at);

CREATE INDEX IF NOT EXISTS review_queue_subject_idx
  ON review_queue (subject_user_id, created_at DESC);
