import { useRef, useState, useCallback } from 'react';

// Camera rPPG is an estimate. It is quality-gated and must not be represented as a
// diagnostic/medical-device measurement without external validation.
export type HRState = 'idle' | 'requesting' | 'measuring' | 'done' | 'error';
export type HRConfidence = 'low' | 'moderate' | 'high';
export interface HRResult { bpm: number; confidence: HRConfidence; signalQuality: number; snrDb: number; sampleRateHz: number; samples: number; }
const HR_WINDOW_SECONDS = 30, HR_MIN_BPM = 40, HR_MAX_BPM = 200;
const mean = (xs:number[]) => xs.reduce((a,b)=>a+b,0)/Math.max(1,xs.length);
const std = (xs:number[]) => { const m=mean(xs); return Math.sqrt(mean(xs.map(x=>(x-m)**2))); };
const clamp=(v:number,lo:number,hi:number)=>Math.max(lo,Math.min(hi,v));
function movingAverage(values:number[], radius:number){const out=new Array(values.length).fill(0);let sum=0;const q:number[]=[];for(let i=0;i<values.length;i++){q.push(values[i]);sum+=values[i];if(q.length>radius*2+1)sum-=q.shift()!;out[i]=sum/q.length;}return out;}
function bandpass(values:number[], sampleRate:number, lowHz:number, highHz:number){const fast=Math.max(1,Math.round(sampleRate/(2*highHz))),slow=Math.max(1,Math.round(sampleRate/(2*lowHz)));const smoothed=movingAverage(values,fast),baseline=movingAverage(smoothed,slow);return smoothed.map((v,i)=>v-baseline[i]);}
function spectralEstimate(signal:number[],sampleRate:number){const minHz=HR_MIN_BPM/60,maxHz=HR_MAX_BPM/60;const stepHz=Math.max(0.0125,sampleRate/Math.max(2048,signal.length));let bestHz=0,bestPower=-Infinity,totalPower=0;for(let f=minHz;f<=maxHz;f+=stepHz){let re=0,im=0;for(let i=0;i<signal.length;i++){const phase=2*Math.PI*f*i/sampleRate;re+=signal[i]*Math.cos(phase);im-=signal[i]*Math.sin(phase);}const power=(re*re+im*im)/Math.max(1,signal.length);totalPower+=power;if(power>bestPower){bestPower=power;bestHz=f;}}const noisePower=Math.max(1e-9,totalPower-bestPower);return{bpm:Math.round(clamp(bestHz*60,HR_MIN_BPM,HR_MAX_BPM)),snrDb:10*Math.log10(Math.max(1e-9,bestPower/noisePower))};}
function robustRppgEstimate(rgb:{r:number;g:number;b:number}[],timestampsMs:number[]):HRResult{
 if(rgb.length<300||timestampsMs.length!==rgb.length)return{bpm:0,confidence:'low',signalQuality:0,snrDb:-Infinity,sampleRateHz:0,samples:rgb.length};
 const duration=Math.max(1e-3,(timestampsMs[timestampsMs.length-1]-timestampsMs[0])/1000),sampleRateHz=rgb.length/duration;
 // requestAnimationFrame may run above 60 Hz on some devices. Use the actual rate;
 // only reject implausible browser timing rather than a strict 60 Hz ceiling.
 if(!Number.isFinite(sampleRateHz)||sampleRateHz<12||sampleRateHz>120)return{bpm:0,confidence:'low',signalQuality:0,snrDb:-Infinity,sampleRateHz,samples:rgb.length};
 const rMean=mean(rgb.map(x=>x.r)),gMean=mean(rgb.map(x=>x.g)),bMean=mean(rgb.map(x=>x.b)),eps=1e-6;
 const r=rgb.map(x=>x.r/Math.max(eps,rMean)-1),g=rgb.map(x=>x.g/Math.max(eps,gMean)-1),b=rgb.map(x=>x.b/Math.max(eps,bMean)-1);
 const xs=r.map((v,i)=>3*v-2*g[i]),ys=r.map((v,i)=>1.5*v+g[i]-1.5*b[i]),sx=std(xs)||1,sy=std(ys)||1;
 const pulse=bandpass(xs.map((x,i)=>x/sx-ys[i]/sy),sampleRateHz,0.67,3.33),signalStd=std(pulse);
 if(!Number.isFinite(signalStd)||signalStd<1e-5)return{bpm:0,confidence:'low',signalQuality:0,snrDb:-Infinity,sampleRateHz,samples:rgb.length};
 const normalized=pulse.map(v=>v/signalStd),{bpm,snrDb}=spectralEstimate(normalized,sampleRateHz),half=Math.floor(normalized.length/2),first=normalized.slice(0,half),second=normalized.slice(normalized.length-half).reverse();let dot=0,aa=0,bb=0;for(let i=0;i<half;i++){dot+=first[i]*second[i];aa+=first[i]**2;bb+=second[i]**2;}const stability=clamp(dot/Math.max(1e-9,Math.sqrt(aa*bb)),-1,1),stabilityScore=(stability+1)/2,snrScore=clamp((snrDb+3)/12,0,1),amplitudeScore=clamp(signalStd*100,0,1),signalQuality=clamp(.55*snrScore+.30*stabilityScore+.15*amplitudeScore,0,1),confidence:HRConfidence=signalQuality>=.70?'high':signalQuality>=.45?'moderate':'low';
 if(confidence==='low'||snrDb<0)return{bpm:0,confidence,signalQuality,snrDb,sampleRateHz,samples:rgb.length};return{bpm,confidence,signalQuality,snrDb,sampleRateHz,samples:rgb.length};
}
export function __testRppg(rgb:{r:number;g:number;b:number}[],timestampsMs:number[]){return robustRppgEstimate(rgb,timestampsMs);}

export function useHeartRate(onResult:(bpm:number,confidence:HRConfidence,quality?:Partial<HRResult>)=>void){
 const[state,setState]=useState<HRState>('idle'),[countdown,setCountdown]=useState(HR_WINDOW_SECONDS),[progress,setProgress]=useState(0),[waveform,setWaveform]=useState<number[]>([]),[error,setError]=useState('');
 const streamRef=useRef<MediaStream|null>(null),videoRef=useRef<HTMLVideoElement|null>(null),canvasRef=useRef<HTMLCanvasElement|null>(null),rgbRef=useRef<{r:number;g:number;b:number}[]>([]),tsRef=useRef<number[]>([]),frameRef=useRef(0),startTimeRef=useRef(0);
 const stop=useCallback(()=>{if(frameRef.current)cancelAnimationFrame(frameRef.current);const stream=streamRef.current;if(stream){const track=stream.getVideoTracks()[0];try{if(track.getCapabilities && 'torch' in track.getCapabilities())track.applyConstraints({advanced:[{torch:false} as any]}).catch(()=>{});}catch{}stream.getTracks().forEach(t=>t.stop());}streamRef.current=null;if(videoRef.current?.parentNode)videoRef.current.parentNode.removeChild(videoRef.current);videoRef.current=null;},[]);
 const start=useCallback(async()=>{setState('requesting');setError('');setCountdown(HR_WINDOW_SECONDS);setProgress(0);setWaveform([]);rgbRef.current=[];tsRef.current=[];try{
   if(!navigator.mediaDevices?.getUserMedia)throw new Error('MEDIA_UNAVAILABLE');
   let stream:MediaStream;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:640},height:{ideal:480},frameRate:{ideal:30}},audio:false});}catch{stream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});}
   streamRef.current=stream;const track=stream.getVideoTracks()[0];try{const caps=track.getCapabilities?.() as any;if(caps?.torch)await track.applyConstraints({advanced:[{torch:true}]} as any);}catch{}
   const video=document.createElement('video');video.srcObject=stream;video.setAttribute('playsinline','true');video.muted=true;video.autoplay=true;video.style.position='fixed';video.style.opacity='0';video.style.pointerEvents='none';video.style.width='1px';video.style.height='1px';video.style.top='-9999px';video.style.left='-9999px';document.body.appendChild(video);videoRef.current=video;await video.play();
   const vw=video.videoWidth||640,vh=video.videoHeight||480,canvas=document.createElement('canvas');canvas.width=vw;canvas.height=vh;canvasRef.current=canvas;startTimeRef.current=performance.now();setState('measuring');
   const captureFrame=()=>{if(!videoRef.current||!canvasRef.current)return;const elapsed=(performance.now()-startTimeRef.current)/1000;if(elapsed>=HR_WINDOW_SECONDS){finish();return;}setProgress(elapsed/HR_WINDOW_SECONDS*100);setCountdown(Math.max(0,Math.ceil(HR_WINDOW_SECONDS-elapsed)));const ctx=canvasRef.current.getContext('2d',{willReadFrequently:true});if(!ctx)return;const w=videoRef.current.videoWidth||vw,h=videoRef.current.videoHeight||vh;if(canvasRef.current.width!==w)canvasRef.current.width=w;if(canvasRef.current.height!==h)canvasRef.current.height=h;ctx.drawImage(videoRef.current,0,0,w,h);const size=Math.max(60,Math.min(w,h)*.28),x=Math.max(0,Math.round((w-size)/2)),y=Math.max(0,Math.round((h-size)/2)),data=ctx.getImageData(x,y,Math.round(size),Math.round(size)).data;let r=0,g=0,b=0;for(let i=0;i<data.length;i+=4){r+=data[i];g+=data[i+1];b+=data[i+2];}const n=data.length/4;rgbRef.current.push({r:r/n,g:g/n,b:b/n});tsRef.current.push(performance.now());setWaveform(prev=>[...prev.slice(-100),g/n]);frameRef.current=requestAnimationFrame(captureFrame);};frameRef.current=requestAnimationFrame(captureFrame);
 }catch(e:any){stop();setState('error');setError(e?.name==='NotAllowedError'?'Camera permission denied. Please allow camera access.':e?.message==='MEDIA_UNAVAILABLE'?'This browser does not support camera access.':'Camera could not be started. Check browser permissions and whether another app is using the camera.');}},[stop]);
 function finish(){stop();const result=robustRppgEstimate(rgbRef.current,tsRef.current);if(result.bpm>0){setState('done');onResult(result.bpm,result.confidence,result);}else{setState('error');setError('Camera is working, but the pulse signal is not reliable enough. Improve lighting, cover the camera lens with the fingertip, keep still, and try again.');}}
 function reset(){setState('idle');setCountdown(HR_WINDOW_SECONDS);setProgress(0);setWaveform([]);setError('');}return{state,countdown,progress,waveform,error,start,stop,reset};
}

export type BRState='idle'|'requesting'|'measuring'|'done'|'error';
function calcBreathRate(samples:{t:number;v:number}[]):number{if(samples.length<60)return 0;const vals=samples.map(s=>s.v),m=mean(vals),centered=vals.map(v=>v-m),sr=samples.length/Math.max(.001,(samples[samples.length-1].t-samples[0].t)/1000);if(sr<10)return 0;const filtered=bandpass(centered,sr,.08,.67),sd=std(filtered);if(sd<1e-6)return 0;const threshold=sd*.35;const minDistance=Math.max(1,Math.floor(sr*1.25));const peaks:number[]=[];for(let i=1;i<filtered.length-1;i++){if(filtered[i]>threshold&&filtered[i]>filtered[i-1]&&filtered[i]>=filtered[i+1]&&(!peaks.length||i-peaks[peaks.length-1]>=minDistance))peaks.push(i);}if(peaks.length<2)return 0;const intervals:number[]=[];for(let i=1;i<peaks.length;i++)intervals.push((peaks[i]-peaks[i-1])/sr);const median=intervals.slice().sort((a,b)=>a-b)[Math.floor(intervals.length/2)];const bpm=60/median;return bpm>=6&&bpm<=40?Math.round(bpm):0;}
export function useBreathRate(onResult:(bpm:number)=>void){const[state,setState]=useState<BRState>('idle'),[countdown,setCountdown]=useState(30),[progress,setProgress]=useState(0),[waveform,setWaveform]=useState<number[]>([]),[error,setError]=useState('');const streamRef=useRef<MediaStream|null>(null),audioCtxRef=useRef<AudioContext|null>(null),analyserRef=useRef<AnalyserNode|null>(null),samplesRef=useRef<{t:number;v:number}[]>([]),frameRef=useRef(0),startRef=useRef(0);const stop=useCallback(()=>{if(frameRef.current)cancelAnimationFrame(frameRef.current);streamRef.current?.getTracks().forEach(t=>t.stop());audioCtxRef.current?.close().catch(()=>{});streamRef.current=null;audioCtxRef.current=null;analyserRef.current=null;},[]);const start=useCallback(async()=>{setState('requesting');setError('');samplesRef.current=[];setWaveform([]);setCountdown(30);setProgress(0);try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('MEDIA_UNAVAILABLE');const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});streamRef.current=stream;const ctx=new AudioContext();audioCtxRef.current=ctx;await ctx.resume().catch(()=>{});const src=ctx.createMediaStreamSource(stream),analyser=ctx.createAnalyser();analyser.fftSize=2048;analyser.smoothingTimeConstant=.2;src.connect(analyser);analyserRef.current=analyser;startRef.current=performance.now();setState('measuring');const capture=()=>{if(!analyserRef.current)return;const elapsed=(performance.now()-startRef.current)/1000;if(elapsed>=30){finish();return;}setProgress(elapsed/30*100);setCountdown(Math.max(0,Math.ceil(30-elapsed)));const buf=new Uint8Array(analyserRef.current.fftSize);analyserRef.current.getByteTimeDomainData(buf);let sum=0;for(const q of buf){const v=(q-128)/128;sum+=v*v;}const rms=Math.sqrt(sum/buf.length);samplesRef.current.push({t:performance.now()-startRef.current,v:rms});setWaveform(prev=>[...prev.slice(-100),rms*300]);frameRef.current=requestAnimationFrame(capture);};frameRef.current=requestAnimationFrame(capture);}catch(e:any){stop();setState('error');setError(e?.name==='NotAllowedError'?'Microphone permission denied. Please allow microphone access.':e?.message==='MEDIA_UNAVAILABLE'?'This browser does not support microphone access.':'Microphone could not be started. Check browser permissions.');}},[stop]);function finish(){stop();const bpm=calcBreathRate(samplesRef.current);if(bpm>0){setState('done');onResult(bpm);}else{setState('error');setError('Microphone is working, but a stable breathing pattern was not detected. Keep the phone near your face in a quiet environment and breathe naturally.');}}function reset(){setState('idle');setCountdown(30);setProgress(0);setWaveform([]);setError('');}return{state,countdown,progress,waveform,error,start,stop,reset};}

export type StepStatus='idle'|'requesting'|'listening'|'permission_required'|'unsupported'|'denied';
export function useStepCounter(onStep:(total:number)=>void,initialTotal=0){const[status,setStatus]=useState<StepStatus>('idle');const stepsRef=useRef(initialTotal),listeningRef=useRef(false),lastMagnitudeRef=useRef(0),lastStepTimeRef=useRef(0),handlerRef=useRef<((e:DeviceMotionEvent)=>void)|null>(null);const start=useCallback(async()=>{if(listeningRef.current)return;if(typeof window==='undefined'||!('DeviceMotionEvent'in window)){setStatus('unsupported');return;}try{const DME=DeviceMotionEvent as typeof DeviceMotionEvent&{requestPermission?:()=>Promise<string>};if(DME.requestPermission){setStatus('requesting');const p=await DME.requestPermission();if(p!=='granted'){setStatus('denied');return;}}handlerRef.current=(e:DeviceMotionEvent)=>{if(!listeningRef.current)return;const a=e.accelerationIncludingGravity;if(!a)return;const mag=Math.sqrt((a.x||0)**2+(a.y||0)**2+(a.z||0)**2),delta=Math.abs(mag-lastMagnitudeRef.current);lastMagnitudeRef.current=mag;const now=Date.now();if(delta>1.15&&now-lastStepTimeRef.current>350){lastStepTimeRef.current=now;stepsRef.current+=1;onStep(stepsRef.current);}};listeningRef.current=true;window.addEventListener('devicemotion',handlerRef.current,{passive:true});setStatus('listening');}catch{setStatus('permission_required');}},[onStep]);const stop=useCallback(()=>{listeningRef.current=false;if(handlerRef.current){window.removeEventListener('devicemotion',handlerRef.current);handlerRef.current=null;}setStatus('idle');},[]);const reset=useCallback(()=>{stepsRef.current=0;lastMagnitudeRef.current=0;lastStepTimeRef.current=0;},[]);return{start,stop,reset,status};}
